# -*- coding: utf-8 -*-
"""FDS6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGVtF54ZqS4QglEgy6y_0AYb3DoIMU3I
"""

import pandas as pd
import numpy as np

employees = pd.DataFrame({
    'Name': ['Ananya', 'Rahul', 'Priya', 'Karthik'],
    'Department': ['HR', 'IT', 'Finance', 'IT'],
    'Age': [25, 29, 27, 31]
})

salaries = pd.DataFrame({
    'Name': ['Ananya', 'Rahul', 'Priya', 'Meera'],
    'Salary': [35000, 52000, 47000, 41000],
    'Bonus': [3000, 5000, 4500, 3500]
})

print('Employee Details:')
display(employees)
print('Salary Details:')
display(salaries)

#inner merge
inner_merge = pd.merge(employees, salaries, on='Name', how='inner')
display(inner_merge)

#left merge
left_merge = pd.merge(employees, salaries, on='Name', how='left')
display(left_merge)

#right merge
right_merge = pd.merge(employees, salaries, on='Name', how='right')
display(right_merge)

#outer merge
outer_merge = pd.merge(employees, salaries, on='Name', how='outer')
display(outer_merge)

#vertical concate
more_employees = pd.DataFrame({
    'Name': ['Arjun', 'Sneha'],
    'Department': ['Sales', 'HR'],
    'Age': [28, 26]
})

vertical_concat = pd.concat([employees, more_employees], axis=0, ignore_index=True)
display(vertical_concat)

#Horizontal concate
attendance = pd.DataFrame({'Attendance_Percent': [95, 88, 92, 85]})
horizontal_concat = pd.concat([employees, attendance], axis=1)
display(horizontal_concat)

#using join
employee_indexed = employees.set_index('Name')
salary_indexed = salaries.set_index('Name')
joined_df = employee_indexed.join(salary_indexed, how='inner')
display(joined_df)