# -*- coding: utf-8 -*-
"""Iris2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4Ld9MQbil9H2TxYUoQ2_i47QOhSDILN
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/iris.csv")
print(df)

# Visualize the correlation matrix using a heatmap.
# Answer the following questions:
# Which two features have the highest positive correlation?
# Which features have weak correlation?
# Are there any negatively correlated features?
# Suppose two features have a correlation of 0.98.

#Display the first five records.
print(df.head())

print(df.dtypes)

#Identify numerical and categorical features.
print("\nNumeric Attributes")
numeric = df.select_dtypes(include=['int64','float64']).columns
print(numeric)

print("\nCategorical Attributes")
categorical = df.select_dtypes(include=['object']).columns
print(categorical)

#Generate the correlation matrix.
print(df[numeric].corr())

# Visualize the correlation matrix using a heatmap.
plt.figure(figsize=(8, 6))
sns.heatmap(df[numeric].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

num = df.select_dtypes(include=['number'])

print("Mean")
print(num.mean())

print("\nMedian")
print(num.median())

print("\nMode")
print(num.mode().iloc[0])
num = df.select_dtypes(include=['number'])
print("Variance")
print(num.var())
print("\nStandard Deviation")
print(num.std())
print("\nRange")
print(num.max() - num.min())
sns.scatterplot(data=df, x='sepal_length', y='petal_length', hue='species')
plt.show()
from sklearn.cluster import KMeans

X = df.iloc[:, :4]

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X)

df['Cluster'] = kmeans.labels_

plt.scatter(df.iloc[:, 0], df.iloc[:, 1], c=df['Cluster'])
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.show()





#