# -*- coding: utf-8 -*-
"""Iris.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19__dHf23jbYp2aaFqBzSV-VDhjS6AN9U
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/iris.csv")
print(df)

print(df.head())

print(df.tail())

print(df.info())

print(df.describe)

print(df.isnull().sum())

print(df.dtypes)

print(df.columns)

print("\nNumeric Attributes")
numeric = df.select_dtypes(include=['int64','float64']).columns
print(numeric)

print("\nCategorical Attributes")
categorical = df.select_dtypes(include=['object']).columns
print(categorical)

#Generate the correlation matrix.
print(df[numeric].corr())

num = df.select_dtypes(include=['number'])

print("Mean")
print(num.mean())

print("\nMedian")
print(num.median())

print("\nMode")
print(num.mode().iloc[0])

num = df.select_dtypes(include=['number'])
print("Variance")
print(num.var())

print("\nStandard Deviation")
print(num.std())

print("\nRange")
print(num.max() - num.min())

sns.scatterplot(data=df, x='sepal_length', y='petal_length', hue='species')
plt.show()

sns.histplot(df['sepal_length'], kde=True)
plt.show()

sns.boxplot(data=df)
plt.show()

corr = df.select_dtypes(include=['number']).corr()

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

from sklearn.cluster import KMeans

X = df.iloc[:, :4]

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X)

df['Cluster'] = kmeans.labels_

plt.scatter(df.iloc[:, 0], df.iloc[:, 1], c=df['Cluster'])
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


X = df[['sepal_length', 'sepal_width', 'petal_width']]
y = df['petal_length']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, pred))

