# -*- coding: utf-8 -*-
"""processing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvmiupUSvk7k24D-4UYX_qtq2cdHirFp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/titanic.csv")
print(df)

print(df.head())

print(df.tail())

print(df.describe())

print(df.info())

print(df.isnull().sum())

print(df.drop_duplicates(inplace=True))
print(df)

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

from sklearn.preprocessing import LabelEncoder, StandardScaler

if 'Cabin' in df.columns:
    df.drop('Cabin', axis=1, inplace=True)
df.dropna(inplace=True)
le = LabelEncoder()
for col in ['Sex', 'Embarked']:
    if col in df.columns:
        df[col] = le.fit_transform(df[col])

# Scale numerical columns
scaler = StandardScaler()
for col in ['Age', 'Fare']:
    if col in df.columns:
        df[col] = scaler.fit_transform(df[[col]])

# Display processed data
print(df.head())